### ISSUE TITLE
All schematics of Non revF can't be downloaded 

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-2chan#102]
![Screenshot_20230908-150717.jpg](https://github.com/rusefi/alphax-2chan/assets/5685108/7cd1b320-18c4-46e2-96b8-ac9eaa81aa44)

Shows some error of invalid file

**Comment by rusefillc** [comment]
https://github.com/rusefi/alphax-2chan/blob/main/boards/alphax_2ch-e/board/alphax_2ch-e-schematic.pdf works for me, how do I reproduce the issue?

please consider full git clone on an adult-sized device

![image](https://github.com/rusefi/alphax-2chan/assets/48498823/99a3a49b-c140-4492-9173-824c9c8245dc)

**Comment by ElDominio** [comment]
This works fine on adult-sized device. Closing
