### ISSUE TITLE
CRITICAL: RevG no power on key on, but yes power if USB is connected

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-2chan#106]
I have two reports of revG not powering on unless 5V is supplied through USB. (One was myself testing on power supply, other was on motorcycle through a dealer)

Steps:
Connect A1 to GND connect A2 to 12v, ECU does not power on

Connecet USB, ECU powers on and stays on if 12v is present, but if power is cycled the ECU will not power until fed power through USB

**Comment by rusefillc** [comment]
@ElDominio can I have any such board?

**Comment by joaodh92** [comment]
This issue it's already identified the problem?

**Comment by rusefillc** [comment]
closing since no board with the problem
