### ISSUE TITLE
 ECU does not power on correctly with 12v, inserting USB makes ECU happy  until next key on

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-2chan#108]
Video of problem here: https://youtube.com/shorts/LHZ4HpVnu9k

Seems the ECU is not waking up correctly on 12v key, once USB is connected it wakes up and stays running fine until next power cycle

**Comment by rusefillc** [comment]
@ElDominio any context?

all 2chan boards on all vehicles?

specific board on specific vehicle?

has it worked before?

how do I reproduce this in NJ?

can you reproduce this with wires without a vehicle?

**Comment by ElDominio** [comment]
RevG

Car was on revC and everything was fine

i have no answer to the other two questions, do you not have a revG board on hand?

BTW i tried full chip erase and the problem persists

**EDIT**
seller now presents a new problem, the thing worked fine until they changed the engine, now it has this issue. I am now guiding them through checking wiring

**Comment by ElDominio** [comment]
I had him power on the unit externally and it powered up correctly; they fucked up wiring. Forgive me for using critical tag i was in panic

**Comment by ElDominio** [comment]
just to update: it was using an external VR converter of my design (uses 5V, gnd, vr+/- and goes to CKP input on ECU); somehow removing it made it work fine. Are there any theories why having it hooked up made the ECU mad?
