### ISSUE TITLE
Usb power no DFU no reset - change to MCU 0.6?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-2chan#12]
![20220112_161624](https://user-images.githubusercontent.com/48498823/149222728-18e37b68-c729-4656-9dfb-894bbaa64449.jpg)

**Comment by andreika-git** [comment]
Current status: L101 should be populated, otherwise STM32 doesn't start.
If L101 is populated, then TLS115 should NOT be populated

**Comment by andreika-git** [comment]
https://community.st.com/s/question/0D50X00009XkhxN/stm32f407vgt6-adc-pins-unused-vrefvrefvddavssa

**Comment by mck1117** [comment]
That's a design mistake - the TLS115 shouldn't power 5VA.  It should power things like the onboard pullups, but not any onboard sensors or logic. For example, right now if you short out the 5v sensor supply, it will incapacitate the STM32's oscillator!

**Comment by mck1117** [comment]
I guess on this revision we will have to run without the TLS and with inductor installed.

**Comment by andreika-git** [comment]
One of the ways to use TLS115 on the rev.A is to cut the +5VA trace going to the input module, and have both L101 and TLS populated.
![image](https://user-images.githubusercontent.com/15104768/149278152-aaa3dbd2-acf1-4779-8387-9c8461185933.png)
In that case:
- The external sensors will be powered from TLS115 and will be protected;
- The STM32 analog core and the internal MAP sensor will be powered from the internal +5VA via L101;
- The input module pullups will be powered internally (which affects only 2Step input);
- Other pullups (CLT, IAT, CAM) will be powered from TLS115.

Also we have another option of cutting a different trace which gives us all pullups and the internal MAP sensor powered from TLS115:
![image](https://user-images.githubusercontent.com/15104768/149281664-b71770d3-39d2-4939-a95e-5a302a42045d.png)

**Comment by rusefillc** [comment]
Plan is to go with 504-PTSA080515V012 fuse for these five boards
