### ISSUE TITLE
Schematics usability

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-2chan#20]
IN_MAP is IN_MAP2 and IN_MAP2 is IN_MAP3?

that's not amazing schematics readability in my opinion.

![image](https://user-images.githubusercontent.com/48498823/149680058-e4979ae9-c197-4759-a1b8-f89ea2bbe9ee.png)

**Comment by rusefillc** [comment]
We cannot change blue names since those are shared Hellen names, let's change black names since those are board specific.

Let's change black "IN_MAP" into "INP_MAP" and black IN_MAP2 into INP_MAP2?

**Comment by mck1117** [comment]
What is INP? Why not internal and external MAP?

**Comment by rusefillc** [comment]
INP_* is the smallest change to remove all conflicts between black and blue

I agree that INT_MAP and EXT_MAP would be even better black net names!

**Comment by andreika-git** [comment]
done
![image](https://user-images.githubusercontent.com/15104768/154328174-f129150b-7a60-472c-8b41-6bd153af6556.png)

**Comment by rusefillc** [comment]
Thank you that's progress for sure!

Open question in black should better be IN_MAP2 or INP_MAP2 at this point I've lost track of what are the arguments supporting which side, at least we've address IN_MAP2 drama
