### ISSUE TITLE
Looks like we have to go HC-0x form factor for bluetooth

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-2chan#23]
still possible to buy good old HC-0x form factor

JDY-31 is it compatible?
JDY-33 seems to be the dominating one, is it compatible in terms of form factor?

i guess on AlphaX it would go on the back side?

**Comment by ElDominio** [comment]
The JD BT boards don't work, I tried both JDY and another BLE compatible HC05 clone, and got it only to work with HC05 (with Realdash)

**Comment by andreika-git** [comment]
done
Switched to JDY-33 footprint
![image](https://user-images.githubusercontent.com/15104768/154309419-882caf8a-6951-4515-b45a-2d61bdb2dd79.png)

**Comment by rusefillc** [comment]
does JDY footprint match HC?

**Comment by andreika-git** [comment]
Not entirely, HC also has bottom pads, and JDY doesn't. But we use only several pads on the left/right, and they match. I guess HC will fit and work too.

**Comment by rusefillc** [comment]
grrrrrrrrrrrrrrrrrrrrr
