### ISSUE TITLE
One board does not power on from USB on arrival

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-2chan#24]
one of five board does not power any LEDs when plugged into USB

**Comment by rusefillc** [comment]
USB VBUS goes only into MCU module. I see VBUS SRV05-4-P-T7 and nothing else

@andreika-git need some troubleshooting instructions in my search for 5v from USB on that defective board

**Comment by andreika-git** [comment]
![image](https://user-images.githubusercontent.com/15104768/150641483-512244d3-2ca2-4bfb-ac1c-57c1a2591525.png)

**Comment by rusefillc** [comment]
@mck1117 can you repair this board? at the moment no life if powered by mini USB. power LED and life expected with mini USB

**Comment by mck1117** [comment]
Fixed, cold solder joint on the USB VBUS pin. Reflowed and the board has power now.
