### ISSUE TITLE
DNP D23 and D24 diodes from injector channels

### ISSUE THREAD

**Issue by mck1117** [rusefi/alphax-2chan#25]
D23 and D24 must be removed. For injectors we want active clamping. We only want freewheel diodes for non-injector solenoids (idle, etc)

**Comment by rusefillc** [comment]
@andreika-git do we need to DNP those?

@ElDominio can you please remove from the board you have?

![image](https://user-images.githubusercontent.com/48498823/151625648-a4afd462-62ef-4aca-a3ad-905f63bd0006.png)

**Comment by mck1117** [comment]
D23/24 are already marked DNP on schematic, looks like it didn't happen. Those footprints can be removed entirely, no reason to keep them.

**Comment by rusefillc** [comment]
@andreika-git is this related to https://github.com/andreika-git/hellen-one/issues/78 ?

**Comment by andreika-git** [comment]
I don't understand why JLC populated them. Here's the final BOM file with the DNP instead of PN, which was sent to the fab:
![image](https://user-images.githubusercontent.com/15104768/151652009-5c0c39fe-eb77-4b92-84b0-6abc3181b091.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/151666404-77655f1c-9493-4645-9d3e-a9ca55293072.png)

**Comment by ElDominio** [comment]
Will remove and report back, the car turned on with them on.

**Comment by andreika-git** [comment]
done, the diodes completely removed
![image](https://user-images.githubusercontent.com/15104768/154310692-62da71b7-763e-4d2b-8090-7dc62dd63740.png)
