### ISSUE TITLE
DNP R213 and R212

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-2chan#26]
![image](https://user-images.githubusercontent.com/48498823/153082614-f95e4e03-c8ff-48db-9e5b-9c5909d27203.png)

these are 5mA each

looks like they're completely unused on this board, we can DNP R213 and R212

**Comment by andreika-git** [comment]
done
![image](https://user-images.githubusercontent.com/15104768/154308901-7d453f29-711f-450a-b748-f27d9ff96808.png)
