### ISSUE TITLE
rev A: fab files component orientation review

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-2chan#27]
at least mini USB seems 90 degrees off?

https://github.com/rusefi/alphax-2chan/commit/85cd90c11d41cd4d58505027f14ebf17c5a46502

**Comment by andreika-git** [comment]
done
Changed the orientation (EasyEDA-compliant)
![image](https://user-images.githubusercontent.com/15104768/154309906-9dc665f3-5a2e-4ae7-8643-4e02c0bea924.png)
