### ISSUE TITLE
increase holes on connector footprint

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-2chan#28]
there are at least two variations of black 24 pin connector, one goes better the other does not work for us as is

What can we do to make footprint more welcoming to wider array of similar connector? can we increase drill size a bit?

**Comment by andreika-git** [comment]
done
All holes are now 1.5mm (+oval pads)
![image](https://user-images.githubusercontent.com/15104768/154310487-21fee0e3-fb81-4758-b191-4e71503d0a47.png)
