### ISSUE TITLE
C4&C7 digital input to support more modes

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-2chan#32]
Change hardware setup to make C4 a full digital input, able to receive 12v/5v or ground when pullup is enabled.

**Comment by mck1117** [comment]
Hardware should already be a full digital input, no? Permanently enabled pullup, tolerant of +-24V or so.

**Comment by ElDominio** [comment]
Some people wire, for example, the positive switch of a nitrous solenoid as a "nitrous engaged" input, so being able to disable the internal pullup is important for usecases like this

**Comment by rusefillc** [comment]
rev A status: C4 response to GND (at the moment we always have pull-up)

**Comment by ElDominio** [comment]
I'd say C7 is fine being as it is (although the pullup should be selectable, some Chryslers have sensors with built-in pullups), C4 does need more modes

**Comment by andreika-git** [comment]
Warning! LEDs will be inversed if pulldown mode is selected for CAM or 2STEP.
