### ISSUE TITLE
C4&C7 pull down mode does not work on rev B

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-2chan#40]
C4 and C7 pull-down test FAIL (?)

regardless of pull-down C7 triggerPrimaryRise increments when I touch +5v and does not increment when I touch GND

measures 0.9v with pull-down=true
measures 1.3v with pull-down=false

**Comment by rusefillc** [comment]
pull-down mode:

R29 side towards main connector 0v
R29 side towards USB  connector 4.8v

R43 side towards main connector 3.2v
R43 side towards USB  connector 0v

pull-down up:

R29 side towards main connector 0.6v
R29 side towards USB  connector 4.8v

R43 side towards main connector 0.0v
R43 side towards USB  connector 0v

**Comment by rusefillc** [comment]
@andreika-git suspects HW issue around Q20 & Q21

**Comment by andreika-git** [comment]
![image](https://user-images.githubusercontent.com/15104768/158324441-39b4e3ab-87c6-4c9f-9d68-c7793fbfe0fc.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/158452256-13b1de9d-ecc6-4c58-8d79-eafe35efe353.png)

**Comment by rusefillc** [comment]
LED works as we expect it to work - in inverted mode with one of operation modes, but main thing LED goes from ON to OFF or from OFF to ON
