### ISSUE TITLE
Pull-ups 5VA or 5VAS in case of TLS115

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-2chan#41]
If we go without R40 with TLS115 do we need all pull-ups on the samve 5V* or not?

![image](https://user-images.githubusercontent.com/48498823/158871263-ce88f484-f552-43dd-8cf5-6e41489c9caa.png)

**Comment by mck1117** [comment]
what is R40

**Comment by rusefillc** [comment]
@mck1117 

![WhatsApp Image 2022-03-17 at 2 18 52 PM](https://user-images.githubusercontent.com/48498823/158908416-1866ba3b-a1d7-4ebb-8185-bf76da269ef4.jpeg)

**Comment by rusefillc** [comment]
this breaks into two questions

1) safety in terms of being exposed
2) power management i.e. which 5v is turned off when board goes stand by

**Comment by rusefillc** [comment]
@andreika-git poke

**Comment by andreika-git** [comment]
TODO: add explanation for +5VAS on the schematics.

**Comment by andreika-git** [comment]
![image](https://user-images.githubusercontent.com/15104768/187863469-8af3b6c5-aba6-4205-91b0-783b1236d35e.png)
