### ISSUE TITLE
Chip Shortage: VND14NV04 alternatives

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-2chan#45]
VND14NV04 is hard to get, are there any direct drop in alternatives?

![image](https://user-images.githubusercontent.com/48498823/160958490-10cfca60-cf13-473d-9f72-7df7afac4812.png)

**Comment by rusefillc** [comment]
@andreika-git would VND10N06 be a drop-in replacement? I know it's an older part :(

**Comment by andreika-git** [comment]
The key difference is Rds: 14NV04 has 0.035 Ohms, and 10N06 has 0.3 Ohms, ten times worse! 
It means that if a current is, say, 5A, then the power dissipation would be 0.875W for our 14NV04 (which is ok) and 7.5W for 10N06 (which is way too high - requires a decent heat sink which we don't have)... Maybe it would still work as injection mosfet, though...

**Comment by rusefillc** [comment]
there is also VND7

and eBay provides us with VND14 for now
