### ISSUE TITLE
Silkscreen IGND reads as "I-GND" not as "IGN-D"

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-2chan#46]
See https://github.com/rusefi/alphax-4chan/issues/15

**Comment by andreika-git** [comment]
@rusefillc Can you please clarify this issue? We do not have "IGND" on 2chan.

**Comment by rusefillc** [comment]
i think it's IGNB on silk which confuses me

so pinout says B

![image](https://user-images.githubusercontent.com/48498823/187486054-cc386627-3117-4c9e-b794-0a17fb48e758.png)

while schematics says 1-2-3-4?

![image](https://user-images.githubusercontent.com/48498823/187486166-e63923a4-55d2-4879-af6a-51767829382b.png)


@ElDominio do you want anything touched? which way do you want to touch things? shall we mention "B" on schematics? shall we change silk from IGNB to something with "2"?

**Comment by ElDominio** [comment]
Close?
