### ISSUE TITLE
D420 let's check rev C orientation files

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-2chan#49]
Do we see anything on 'produce....png' between https://github.com/rusefi/alphax-2chan/tree/main/boards/alphax_2ch-b/board and https://github.com/rusefi/alphax-2chan/tree/main/boards/alphax_2ch-c/board ?

**Comment by andreika-git** [comment]
This is our original orientation, and it's correct.
![image](https://user-images.githubusercontent.com/15104768/162132082-685d72ea-ec75-4204-a321-e515380b7e58.png)
The fab guys are probably misleaded by the silkscreen...

**Comment by rusefillc** [comment]
so both B and C JLC have flipped on preview files

and only on C they have actually flipped
