### ISSUE TITLE
Pin C4 not behaving correctly? Need testing?

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-2chan#50]
I have both a revA and a revB with issues on the Launch Control input where it stays engaged no matter what. I haven't been able to test much, but Tercel and Corolla both stay with launch control engaged if I enable launch control. Will update with more tests, but if any bench tests can be done it would be great

**Comment by andreika-git** [comment]
What's the value of the setting 'boardUse2stepPullDown'? Is it "With Pull Down" or "With Pull Up"?

**Comment by ElDominio** [comment]
1) Pretty sure I have it as "With Pullup", since we wired it to a switch to ground

2) Have not tested revC yet

**Comment by andreika-git** [comment]
1. Does the revB board have the required fix of Q21 transistor? (see https://github.com/rusefi/alphax-2chan/issues/40)

2. Did you set the Launch Control settings correctly? 
  a) "Activation Mode" should be set to "Switch Input"
  b) "Switch Input" pin should be set to "C4 - 2STEP"

Currently there is no option for "Switch Input inverted" in the firmware, although we already have "Clutch Input inverted". That's why your switch may act in inverted mode, and launch control may be engaged all the time except when activated. Maybe we should ask @rusefillc to add the inverting pin mode option...

3. Can you please try the "readpin PF11" command in the rusEFI Console? Please run it twice with the switch enabled and disab led. This will check the voltage on the input pin without any Launch Control logic.

**Comment by rusefillc** [comment]
@ElDominio I've made the change we can now adjust Launch control pin mode

Please update to latest firmware, please select inverted pin mode, please report back.

**Comment by rusefillc** [comment]
@andreika-git reminded me that we need actual code for that not just UI :)

**Comment by ElDominio** [comment]
I updated, used it as clutch input and now it works fine
![image](https://user-images.githubusercontent.com/5685108/164069302-c8f6bc25-5114-464c-a5e2-ca8514f46fa3.png)

**Comment by andreika-git** [comment]
It would be great if you could test with the new "Switch input inverted" option too...

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/164070512-627c691a-6620-4735-9d24-e3aa10e4b515.png)


it disables as an option if i use switch input mode

**Comment by andreika-git** [comment]
We'll fix it, thanks!

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/164110692-e04da360-0a86-4157-9e42-4be82effd761.png)

That is fixed, but in switch mode it still doesn't listen to what I select. It is active when 5v is present, inactive when GND, and I need the opposite

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/164111204-ea9716e7-8582-4490-b44a-853ce84161df.png)


When I set it as clutch input, it sets the one as clutch down too and it throws a critical error lol

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/164111326-7c342349-2402-4c65-a1b2-22bd29f0e8e9.png)

If I set it as clutch input, the settings in Misc sensors gets auto-set, and rusEFI throws a critical error

![image](https://user-images.githubusercontent.com/5685108/164111396-546f4830-9756-485b-9e92-e27b68a163fd.png)

**Comment by rusefillc** [comment]
its greyed but still selected. you need to fully unselect when changing mode

**Comment by rusefillc** [comment]
OK so original problem is that we launch button "inverted" is missing! 


should be
![image](https://user-images.githubusercontent.com/48498823/164119216-c2a12200-3180-403a-ad88-61df7fe1a137.png)

and we have

![image](https://user-images.githubusercontent.com/48498823/164119276-f2574e57-4766-4d0b-b34d-9dee04041a23.png)

**Comment by rusefillc** [comment]
@ElDominio just added logic to hand the new "inverted" flag.

Overall we have three things for each switch:
1. pin
2. inverted or not
3. physical pull ups

**Comment by rusefillc** [comment]
@ElDominio how does it look with latest changes?

**Comment by rusefillc** [comment]
closing for now?

**Comment by ElDominio** [comment]
New update is great and works great 😁
