### ISSUE TITLE
Q3 drama - long term fix

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-2chan#52]
![image](https://user-images.githubusercontent.com/48498823/165997368-1a1de511-ecc1-4ff6-ae24-af7170778878.png)

![image](https://user-images.githubusercontent.com/48498823/165997383-cb8ea165-597b-4d76-9609-395f63232ecc.png)

**Comment by rusefillc** [comment]
@ElDominio any additional info?

**Comment by rusefillc** [comment]
all these pull-ups are NOT protected from +5v on the wire while ECU is not powered by +12v

Overall need more info :)

**Comment by ElDominio** [comment]
Was used to run Tacho in 12v mode.

Was on Corolla 1ZZ 2003

The ECU also doesn't read RPM anymore, maybe thanks to this?

**Comment by rusefillc** [comment]
Yes this is about tach for sure

Do you have a wiring diagram for that 2003 1ZZ?

**Comment by ElDominio** [comment]
All the info I have at this point:

Car was running fine in the shop, tach was also working fine, set as 12V. 
Owner has some odd cranking issues the next day, tech tells owner to check a few wires
Car never started again
Car taken to our shop, tech finds damage on ECU.

The car has very bad sync issues now (VR crank). Could anything here damage anything sync related?

I will be at the shop on Tuesday

**Comment by mck1117** [comment]
@andreika-git what change was made in your commit? Short description in commit message would be great...

It's possible we exceeded the maximum allowed V_gs on the mosfet - the maximum allowed is +-12v, which we exceed if the pullup is enabled and the alternator charges the battery at 14-15v or whatever. It's certainly at least marginal.

**Comment by ElDominio** [comment]
The strange this is it ran fine until the owner took it home... is this something that would take a while to kill?

**Comment by rusefillc** [comment]
if it's about MOSFET dying from voltage
@mck1117 says

The mosfet may have
1 million hours failure at 12 volts
1000 hours at 13v
10 hours at 14v
1 minute at 15v
1 second 16v
0.001 second 20v

**Comment by andreika-git** [comment]
> @andreika-git what change was made in your commit? Short description in commit message would be great...

The idea of my fix is: if +12V_RAW is not a power source but a load (when connected to a car harness), then high current may flow through Q3 mosfet from 5V to 12V...
![image](https://user-images.githubusercontent.com/15104768/166158859-74ce4288-1056-4582-ab3d-bd3e42ca2ab8.png)

**Comment by mck1117** [comment]
@andreika-git yes, that's also a possible answer.

This would solve both issues:

![image](https://user-images.githubusercontent.com/568254/166163205-c769a17e-de8d-4e88-b1cf-76d8eaf8fa46.png)

1. add a diode between Q3 and D28_1, so that current can only flow out of the pullup.
2. Add a zener between Q3 pins 1 and 3 to limit V_gs
3. Add a resistor between Q1 and Q3 to limit current in the zener in (2)

**Comment by ElDominio** [comment]
Assuming this happened, could it take down the processor with it? Car has very bad sync issues (sometimes reads, but it never reads enough to run)

**Comment by ElDominio** [comment]
Engine not running was due to incorrect gap override, @mck1117  advised and that was fixed, the car runs again.

Question, would using tach output at 5v and using that signal for an external circuit work? could this ECU still output a 5v wave?

**Comment by mck1117** [comment]
I thiiiiiink that would work? If Q3 failed open-circuit, then it should still work as a 5v pullup output.

**Comment by ElDominio** [comment]
Checked and that's quite probably correct. The output still outputs a 5v wave, so we'll use that with an external 2222 to drive the tacho, thanks

**Comment by rusefillc** [comment]
@andreika-git do you want to upgrade Q3 similar to part suggested at #53

**Comment by mck1117** [comment]
> @andreika-git do you want to upgrade Q3 similar to part suggested at #53

my recommendation above about adding a zener would mean the current Q3 is OK, and would protect against transients above 20v anyway

**Comment by ElDominio** [comment]
BTW

We did the external circuit with a 2222 and it's working fine again :)

**Comment by andreika-git** [comment]
I think @mck1117's method is more universal and preferred.

**Comment by andreika-git** [comment]
On the other side, we also have other p-channel mosfets:
![image](https://user-images.githubusercontent.com/15104768/166416068-f83cdd3c-eaab-4c42-9f2a-ef3d23c296fc.png)
And it seems we don't have free space for fitting additional components for these (without major pcb redesign)...
Maybe we could limit the +12V source used for pull-ups? We could use a free PSM712 (TVS), which would allow to use SI2347DS mosfets. Of course +$3 will be added to the price...

**Comment by andreika-git** [comment]
Something like this:
![image](https://user-images.githubusercontent.com/15104768/166420581-036811f5-87fe-4ddf-b408-d13ce2590b1b.png)

**Comment by mck1117** [comment]
I see you've also added a resistor divider to the gate of Q3 - that's probably enough to avoid problems. The TVS probably isn't necessary, as that circuit is now 100% good up to at least 24v input.

**Comment by andreika-git** [comment]
> I see you've also added a resistor divider to the gate of Q3 - that's probably enough to avoid problems. The TVS probably isn't necessary, as that circuit is now 100% good up to at least 24v input.

Yes, but the TVS is to protect other p-channel mosfets: q4, q5, q16, q17 - they didn't have a spare resistor, and it's not easy to find a free space for additional ones:
![image](https://user-images.githubusercontent.com/15104768/166868760-41dc426f-fef4-4aeb-9c0b-3a5baa30a08d.png)
But maybe you're right and I should try harder and solve the problem by squeezing in the resistors...

**Comment by andreika-git** [comment]
Added more gate resistors. Now we can use our favorite AO3401 as before.
![image](https://user-images.githubusercontent.com/15104768/167480732-e764fd1e-d548-482a-a347-427afa87b9f5.png)

**Comment by rusefillc** [comment]
i guess time to close?
