### ISSUE TITLE
Q3 drama - suggest mods for A, B and C boards

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-2chan#53]
it's suggested to mod boards for 5v or 12v

5v tach: remove Q3, keep diode D28

12v tach: keep Q3, remove diode D28

**Comment by rusefillc** [comment]
@andreika-git please confirm ^^^

**Comment by rusefillc** [comment]
there is also a suggestion to swap Q3 for vishay SI2347DS-T1-BE3 is similar but has 20V max V_gs part

**Comment by andreika-git** [comment]
> there is also a suggestion to swap Q3 for vishay SI2347DS-T1-BE3 is similar but has 20V max V_gs part

And also Q4, Q5, Q16, Q17.

**Comment by rusefillc** [comment]
i guess time to close?
