### ISSUE TITLE
U1 TLS115 rev D BOM issue

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-2chan#66]
![image](https://user-images.githubusercontent.com/48498823/193877938-cff0d744-7f86-4ef0-a590-c1e69dc95c5b.png)

Did we forget U1 BOM? :(

**Comment by rusefillc** [comment]
#64

**Comment by ElDominio** [comment]
https://github.com/rusefi/alphax-4chan/blob/main/bom_replace_alphax_4ch-d.csv

Not in BOM, and I cant figure which one it is

![image](https://user-images.githubusercontent.com/5685108/193999149-46606937-1d53-4f29-a410-ab058074f025.png)
 Not in stock in Digikey if this is it

**Comment by rusefillc** [comment]
we use 10 pad package here not the 8 pad package

digikey TLS115D0LDXUMA1 please

**Comment by rusefillc** [comment]
@andreika-git please fix master kicad files and fix https://github.com/rusefi/alphax-2chan/blob/main/boards/alphax_2ch-d/board/alphax_2ch-d-BOM.csv manually
