### ISSUE TITLE
conditioned crank test pad prior to rev D

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-2chan#67]
@ElDominio needs a way to hack a crank test pad prior to rev D https://github.com/rusefi/alphax-2chan/issues/63

**Comment by rusefillc** [comment]
so we need some resistor or capacitor either on the output of vr-descrete or on IN_CRANK input module input side

![image](https://user-images.githubusercontent.com/48498823/194725681-b6a300c4-a927-4b1e-a495-3f640a55b8ad.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/194725716-53c83f96-7501-4879-8845-69f04e441f2e.png)

**Comment by rusefillc** [comment]
@ElDominio that bright green LED looks like it's the output, it's apparantly supposed to be blinking with crank?

one of the sides of it or maybe any side would make a great test point

**Comment by ElDominio** [comment]
i love you
