### ISSUE TITLE
Change USB connector to C2764612 , USB-C 

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-2chan#68]
Change USB connector to C2764612 , USB-C type since I have too many USB-C cables laying around

**Comment by rusefillc** [comment]
[https://jlcpcb.com/parts/componentSearch?searchTxt=C2764612%20 is ](https://jlcpcb.com/partdetail/XkbConnectivity-U262_061N4BVC11/C2764612)

**Comment by rusefillc** [comment]
See also https://github.com/rusefi/alphax-4chan/issues/78

**Comment by Qwerty-OFF** [comment]
This connector is for power only. It does not contain data lines.

**Comment by rusefillc** [comment]
@Qwerty-OFF please do NOT change for rev-E anyway, we have enough risk as is :)

**Comment by ElDominio** [comment]
https://jlcpcb.com/partdetail/Dealon-USB_TYPE_C018/C2927038 compatible

**Comment by Qwerty-OFF** [comment]
#92
