### ISSUE TITLE
Bump PCB version to E

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-2chan#72]
Also board id see https://github.com/andreika-git/hellen-one/commit/d95638694cd19c75c944968631315f1ccf72bfce

**Comment by Qwerty-OFF** [comment]
@rusefillc Missing board_id_alpha2ch-e.csv in https://github.com/andreika-git/hellen-one/tree/master/board_id/generated
How to fix?

**Comment by rusefillc** [comment]
@Qwerty-OFF let me fix in 4 hours

**Comment by rusefillc** [comment]
@Qwerty-OFF should be better now

**Comment by Qwerty-OFF** [comment]
Done
