### ISSUE TITLE
One rev C board has returned to NJ

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-2chan#73]
@ElDominio what seems to be the problem?

**Comment by ElDominio** [comment]
No TPS reading

**Comment by rusefillc** [comment]
https://rusefi.com/docs/pinouts/hellen/alphax-2chan/ I assume B5

**Comment by ElDominio** [comment]
Yes, i traced to processor and saw tps voltage, but no reading on ECU. Read sometimes for a small time then back to nothing

**Comment by rusefillc** [comment]
Solved: op-amp has not enough solder. works with a drop of solder paste now!
