### ISSUE TITLE
Add lin module with a pad

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-2chan#75]
if we have space we can add LIN module with a pad

open question if same UART with BT with jumpers or else

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/215279955-014f9aca-800f-400a-891e-05d7e34f836e.png)

**Comment by Qwerty-OFF** [comment]
![image](https://github.com/rusefi/alphax-2chan/assets/4116383/8b3a8f51-fa45-47ce-bf42-677121b60af5)
