### ISSUE TITLE
rev E test log

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-2chan#76]
* PROG button works - blue LED blinks
* works from external +12v power supply seems happy! https://github.com/andreika-git/hellen-one/issues/246
* +5 goes out
* TPS sensor works - OPEN QUESTION WHAT analog mux considerations we have here?!
* two injectors are clicking in bench test
* SD card does NOT work so far probably firmware needed?

@ElDominio FYI

**Comment by rusefillc** [comment]
Fun fact - rev A has on-board baro (another one, not the on-board MAP) and on-board accelerometer (maybe without firmware support?!)

**Comment by Qwerty-OFF** [comment]
SD card is now connected to SPI1

**Comment by rusefillc** [comment]
@ElDominio did you have a chance to put one on a real vehicle? VR vehicle or non VR vehicle?

**Comment by ElDominio** [comment]
Tomorrow, dual hall

**Comment by rusefillc** [comment]
Need a VR test as well :)

**Comment by mck1117** [comment]
> Need a VR test as well :)

All VR since forever is broken without the extra caps bodged on, which should happen to every pre-0.4-vr ECU out there if you want to use VR on it.

**Comment by rusefillc** [comment]
@mck1117 somehow we had happy VR experience on some cars?

@ElDominio did we have _any_ happy VR vehicles on Alpha?

**Comment by mck1117** [comment]
One edge was better than the other. If you are wired to use the good edge and lucky enough, it'd usually work without the caps. Unlucky or wired backwards you need the caps to get a usable signal at all.

**Comment by rusefillc** [comment]
@ElDominio poke need real vehicle 2chan rev E results please

**Comment by ElDominio** [comment]
Once I have them on my hands
