### ISSUE TITLE
Tach LED not blinking?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-2chan#82]
https://github.com/rusefi/alphax-4chan/issues/95 makes me wonder

**Comment by Qwerty-OFF** [comment]
The LED is not installed correctly. It needs to be fixed in the next revision, just like in 4chan.
On the rev e board, D1 and D9 must be removed, otherwise there may be problems with the operation of the tachometer output.

**Comment by Qwerty-OFF** [comment]
Fixed
