### ISSUE TITLE
revF wishlist

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-2chan#86]
My requests for "final" revision of 2chan

-> USB-C port instead of mini USB https://github.com/rusefi/alphax-2chan/issues/92

-> use expansion module https://github.com/rusefi/alphax-2chan/issues/93

-> ~~Built in baro onboard, so this menu is used  fixed by https://github.com/rusefi/alphax-2chan/issues/87~~

* Default Tacho to 12v, add a removable component to change to 5V

**Comment by ElDominio** [comment]
Move MAP location nearer to the middle of the board or close to connector, to evade damage during shipping

![IMG-20230315-WA0012.jpg](https://user-images.githubusercontent.com/5685108/225400735-826e16c2-6b24-4376-a02a-d257ab2c8c48.jpg)

Like so
![Screenshot_20230315-135757.jpg](https://user-images.githubusercontent.com/5685108/225401029-329a16ae-a5f9-4d7a-b585-693177313db7.jpg)

**Comment by rusefillc** [comment]
@Qwerty-OFF does 2chan need any VR/hall magic on top of rev-E? or is it that all hard cases are 4chan anyway?

**Comment by ElDominio** [comment]
I think revE is working quite well, have not ween a need for anything more than we have right now?

**Comment by rusefillc** [comment]
Ordering rev F now
