### ISSUE TITLE
support both VR and hall crank

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-2chan#9]
While CAM is always Hall, we need to support both VR and hall crank

**Comment by rusefillc** [comment]
@mck1117 poke :)

**Comment by andreika-git** [comment]
We've implemented a universal input for CRANK:
1) as VR-input, or
2) as two separate Hall inputs (with controllable pull-ups) for CRANK+ and CRANK-
And also a hall input for CAM.
