### ISSUE TITLE
Move MAP to safer location

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-2chan#94]
![image](https://user-images.githubusercontent.com/48498823/236908070-d82dfabb-79ce-4446-829d-1038b0bd1cd2.png)

**Comment by Qwerty-OFF** [comment]
![image](https://github.com/rusefi/alphax-2chan/assets/4116383/a2cc3453-c6c0-46b0-a064-6eb2928b6a21)

**Comment by rusefillc** [comment]
@Qwerty-OFF do we have a chance to add a huge hole under the sensor like before or is it not trivial?

**Comment by rusefillc** [comment]
![image](https://github.com/rusefi/alphax-2chan/assets/48498823/795bc756-c57b-42c9-a906-2c213bc7fa45)

**Comment by Qwerty-OFF** [comment]
4mm hole
<img width="175" alt="image" src="https://github.com/rusefi/alphax-2chan/assets/4116383/4420ffb0-f5d2-43a6-ade4-d9790b228667">
