### ISSUE TITLE
CRITICAL: 2chan revE started, not pulsing Coil1 or 2 after running for a few seconds

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-2chan#96]
https://github.com/rusefi/alphax-2chan/assets/5685108/716a2cc6-083f-4eb1-a867-26d8ce000559

This is all I have since they are beginning engineering students

I made this simulation log, I see coilstates changing, but physically only can see 2.5 when pulsing 2seconds on/off in Bench Test mode (no 5v)

[simulationlog.zip](https://github.com/rusefi/alphax-2chan/files/11470845/simulationlog.zip)

**Comment by ElDominio** [comment]
update;

channel 1 is back to life, but channel 2 is still dead. What can they check?

**Comment by rusefillc** [comment]
do they have a digital multimeter with frequency measurement? they should play with self-stimulation and DMM reporting frequency at proper relevant points

**Comment by ElDominio** [comment]
Self stim at what RPM? I think they can do that

**Comment by rusefillc** [comment]
600
1200
2400

Frequency should change accordingly

**Comment by Qwerty-OFF** [comment]
Is only one board tested? We have duplicate LEDs in mega-mcu144, do they behave the same way?

![image](https://github.com/rusefi/alphax-2chan/assets/4116383/9724fbac-df7d-4960-ae7d-a4a05d12fc8a)

**Comment by ElDominio** [comment]
This board is with a Formula SAE team in Mexico so not easy to test heh

They reported the engine ran for about 10 seconds, then ignition channels died. 

They are using one of these igniters: https://www.efihardware.com/products/2270/Bosch-4-Channel-Ignitor

Is there any component that can be replaced or any point that can be probed? I will take one of my igniters to the FSAE competition (and a spare ECU) but it's a bit odd.

**Comment by Qwerty-OFF** [comment]
You can check the signal next to U460. On the right are inputs from the MCU, on the left are outputs through series resistors of 10 ohms. If there is a signal on the right and none on the left, replacing U460 might help.

Does the team use one output to simultaneously control two coils?

![image](https://github.com/rusefi/alphax-2chan/assets/4116383/f17000b7-7cdc-4f81-93c1-c68d30b45184)

**Comment by Qwerty-OFF** [comment]
You can also check the self-recovering fuses F1 and F2.
![image](https://github.com/rusefi/alphax-2chan/assets/4116383/724bfd2a-be7d-481b-9459-dd3936d58aa7)

**Comment by ElDominio** [comment]
> You can check the signal next to U460. On the right are inputs from the MCU, on the left are outputs through series resistors of 10 ohms. If there is a signal on the right and none on the left, replacing U460 might help.
> 
> Does the team use one output to simultaneously control two coils?
> 
> ![image](https://github.com/rusefi/alphax-2chan/assets/4116383/f17000b7-7cdc-4f81-93c1-c68d30b45184)
> 
> 

Yep since it's a 4 cylinder

**Comment by ElDominio** [comment]
![IMG_20230519_091408.jpg](https://github.com/rusefi/alphax-2chan/assets/5685108/d25ee6ec-b9f1-432e-8fb6-b4c02d07ce23)

I believe this is somehow the culprit, have the ecu on hand for testing

**Comment by ElDominio** [comment]
It was the culprit, and the coi2 output died along with it
