### ISSUE TITLE
ibom 3D PCB view degradation

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-2chan#97]
https://rusefi.com/docs/ibom/alphax_2ch-e-ibom.html click PCB - stm32 is displayed properly
https://rusefi.com/docs/ibom/alphax_2ch-f-ibom.html click PCB - we have stuff shifted, we now have main connector which we did not see before?

**Comment by rusefillc** [comment]
@Qwerty-OFF ты знаешь, где трогать - или надо @andreika-git трогать?

**Comment by Qwerty-OFF** [comment]
Я в кикаде переставил в левый нижний угол метки начала координат, которые почему-то были не в нем. Допускаю что дело в этом, но что делать с этим не знаю
<img width="74" alt="image" src="https://github.com/rusefi/alphax-2chan/assets/4116383/ef89c634-de54-460e-a474-1771a4b19375">

**Comment by rusefillc** [comment]
@andreika-git нужна может быть только документация, без помощи?

**Comment by andreika-git** [comment]
После переставления начала координат нужно при экспорте VRML убедиться, что указанные там координаты совпадают с этим началом

**Comment by andreika-git** [comment]
https://github.com/andreika-git/hellen-one/wiki/fix-image-offset-howto

**Comment by andreika-git** [comment]
Fixed!
There were several issues: wrong image offset and wrong offset of the main connector's 3d-model.

**Comment by rusefillc** [comment]
https://github.com/rusefi/alphax-2chan/commit/12e65748e2b58275bfda090a919dd1a521cffd58 touches only total offset unless I am missing something? where do we touch main connector 3D model?

**Comment by andreika-git** [comment]
> [12e6574](https://github.com/rusefi/alphax-2chan/commit/12e65748e2b58275bfda090a919dd1a521cffd58) touches only total offset unless I am missing something? where do we touch main connector 3D model?

It's inside the .kicad_pcb file. The 3d model itself stays the same, it's the offset used for the component was wrong:

![image](https://github.com/rusefi/alphax-2chan/assets/15104768/2690c1bd-233d-49b5-8147-ce09d8b3a179)
